### ISSUE TITLE
Familiarize with Making a 2D Unity Game.

### ISSUE THREAD

**Issue by minghan108** [Evan-HR/Handits#1]
Here is a good tutorial for making a TileBased 2D game.

Link: [https://www.youtube.com/watch?v=on9nwbZngyw](url)

**Comment by bustinjurkz** [comment]
Everyone should watch that tutorial and make the game on Unity.  Comment when you've completed

**Comment by zjkong** [comment]
Before we dive into developing a real game, we should get familiar with some fundamental knowledge in Unity.

Acceptance criteria: Go through any online unity 2D platformer tutorial and presents its final result to other team members.

**Comment by bustinjurkz** [comment]
There's a "2D Roguelike" tutorial under "learn" in Unity. it seems to be a built-in tutorial.  Could be useful!

**Comment by bustinjurkz** [comment]
I got an asset to bounce off another body.  Going to get a character to control using the keyboard in a custom script (from the other Unity tutorial i was working on) and then I think i should be sorta caught up in the basics
