### ISSUE TITLE
Start Shell Menu

### ISSUE THREAD

**Issue by Dstew4444** [Evan-HR/Handits#10]
-Starter menu 
-'Press Play' and enter the player movement scene
-5 points
-Requires

**Comment by Evan-HR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #10: Start Shell Menu](https://trello.com/c/3CzAxCQs/30-issue-10-start-shell-menu)

**Comment by Evan-HR** [comment]
Dustin did this. Good job Dustin!
