### ISSUE TITLE
Basic Enemy

### ISSUE THREAD

**Issue by Dstew4444** [Evan-HR/Handits#13]
-Spawn a basic enemy capable of moving towards the player
- 5 points
-Requires: Issues 8, 11 (Player gameobject, Basic environment)

**Comment by Evan-HR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #11: Create Scene Navigator](https://trello.com/c/clSkTlXF/31-issue-11-create-scene-navigator)
