### ISSUE TITLE
Preliminary Game Design Steps

### ISSUE THREAD

**Issue by bustinjurkz** [Evan-HR/Handits#14]
From the Baldwin Game Design Template, we could roughly write the following sections by Friday Oct 5th:

Section I, Section II basics, 6.1.1, 6.1.2, 6.1.3, 6.2, 6.3, 8.2, 8.3, 8.4, 8.5, Section VI,

**Comment by Evan-HR** [comment]
Preliminary Game Design Doc version was made; it's a living document however so will be maintained throughout
