### ISSUE TITLE
Create Player 

### ISSUE THREAD

**Issue by Dstew4444** [Evan-HR/Handits#8]
-Establish a player game object 
-Implement player movement
-collision detection
-acceleration
-5 points
-Required: Issue No. 7

**Comment by Evan-HR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #8: Player Movement](https://trello.com/c/ZenEi4F5/28-issue-8-player-movement)

**Comment by Evan-HR** [comment]
Danny made a working example environment with moving character that behaves as the task desired. Specifics of gameplay acceleration/jump height etc. will be further specified later.
