### ISSUE TITLE
Camera Functionality

### ISSUE THREAD

**Issue by Dstew4444** [Evan-HR/Handits#9]
-Camera tethered to player game object
-Orthographic camera (one per player)
-3 points
-Requires: Issue No. 8

**Comment by Evan-HR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #9: Camera Functionality](https://trello.com/c/DuAvCSit/29-issue-9-camera-functionality)

**Comment by Evan-HR** [comment]
Kong properly implemented this, it is in our current version
